#!/usr/bin/env python3
"""Import VFD Master Excel into app Dart data files.

Source (default):
  D:\\VFD_Master_Database_Final - Copy.xlsx

Sheets used (SupportedVendors release):
  Yaskawa, INVT, Danfoss, Schneider, Allen Bradley, Siemens

Outputs:
  tools/excel_master_parsed.json
  lib/data/datasources/vfd_master_from_excel.dart
  lib/data/datasources/vendor_models_from_excel.dart
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

try:
    import openpyxl
except ImportError:
    import subprocess

    subprocess.check_call([sys.executable, "-m", "pip", "install", "openpyxl", "-q"])
    import openpyxl

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_XLSX = Path(r"D:\VFD_Master_Database_Final - Copy.xlsx")
SUPPORTED = [
    "ABB",
    "Yaskawa",
    "INVT",
    "Danfoss",
    "Schneider",
    "Allen Bradley",
    "Siemens",
    "Mitsubishi",
    "Delta",
]


def _escape_dart(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'")


def _is_data_row(row: tuple) -> bool:
    if not row or row[0] is None:
        return False
    first = row[0]
    if isinstance(first, str):
        t = first.strip()
        if "▶" in t or "VARIABLE FREQUENCY" in t or "Current Active" in t:
            return False
        if t.startswith("S.No"):
            return False
    return isinstance(first, (int, float))


def parse_workbook(path: Path) -> dict[str, list[dict]]:
    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    out: dict[str, list[dict]] = {}
    for vendor in SUPPORTED:
        if vendor not in wb.sheetnames:
            print(f"WARN: missing sheet {vendor}")
            continue
        ws = wb[vendor]
        models: list[dict] = []
        for row in ws.iter_rows(values_only=True):
            if not _is_data_row(row):
                continue
            name = str(row[1]).strip() if row[1] else ""
            if not name:
                continue
            models.append(
                {
                    "name": name,
                    "minKw": float(row[2] or 0),
                    "maxKw": float(row[3] or 0),
                    "powerRatings": str(row[4] or "").strip(),
                    "app": str(row[5] or "").strip(),
                    "status": str(row[6] or "").strip(),
                    "commCard": str(row[8] or "").strip(),
                    "defaultProto": str(row[9] or "").strip(),
                }
            )
        out[vendor] = models
        print(f"  {vendor}: {len(models)} models")
    wb.close()
    return out


def emit_vfd_master_dart(data: dict[str, list[dict]], dest: Path) -> None:
    lines = [
        "// GENERATED by tools/import_excel_master.py — do not edit by hand.",
        "// Source: VFD_Master_Database_Final Excel workbook.",
        "",
        "import 'vfd_model_data.dart';",
        "",
        "class VfdMasterFromExcel {",
        "  VfdMasterFromExcel._();",
        "",
        "  static final Map<String, List<VfdModelData>> vendors = {",
    ]
    for vendor, models in data.items():
        lines.append(f"    '{_escape_dart(vendor)}': [")
        for m in models:
            lines.append(
                "      VfdModelData("
                f"\n          name: '{_escape_dart(m['name'])}',"
                f"\n          minKw: {m['minKw']},"
                f"\n          maxKw: {m['maxKw']},"
                f"\n          powerRatings: '{_escape_dart(m['powerRatings'])}',"
                f"\n          app: '{_escape_dart(m['app'])}',"
                f"\n          status: '{_escape_dart(m['status'])}',"
                f"\n          commCard: '{_escape_dart(m['commCard'])}',"
                f"\n          defaultProto: '{_escape_dart(m['defaultProto'])}',"
                "\n        ),"
            )
        lines.append("    ],")
    lines.extend(
        [
            "  };",
            "}",
            "",
        ]
    )
    dest.write_text("\n".join(lines), encoding="utf-8")


def emit_vendor_models_dart(data: dict[str, list[dict]], dest: Path) -> None:
    lines = [
        "// GENERATED by tools/import_excel_master.py — do not edit by hand.",
        "",
        "class VfdModelInfo {",
        "  final String name;",
        "  final String series;",
        "  final String description;",
        "  final double minKw;",
        "  final double maxKw;",
        "",
        "  const VfdModelInfo({",
        "    required this.name,",
        "    required this.series,",
        "    required this.description,",
        "    required this.minKw,",
        "    required this.maxKw,",
        "  });",
        "}",
        "",
        "class VendorModelsFromExcel {",
        "  VendorModelsFromExcel._();",
        "",
        "  static const Map<String, List<VfdModelInfo>> models = {",
    ]
    for vendor, models in data.items():
        lines.append(f"    '{_escape_dart(vendor)}': [")
        for m in models:
            series = m["name"].split("(")[0].strip() if "(" in m["name"] else m["name"]
            lines.append(
                "      VfdModelInfo("
                f"\n        name: '{_escape_dart(m['name'])}',"
                f"\n        series: '{_escape_dart(series)}',"
                f"\n        description: '{_escape_dart(m['app'])}',"
                f"\n        minKw: {m['minKw']},"
                f"\n        maxKw: {m['maxKw']},"
                "\n      ),"
            )
        lines.append("    ],")
    lines.extend(["  };", "}", ""])
    dest.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    xlsx = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_XLSX
    if not xlsx.exists():
        print(f"ERROR: Excel not found: {xlsx}")
        sys.exit(1)

    print(f"Reading {xlsx}")
    data = parse_workbook(xlsx)

    json_path = ROOT / "tools" / "excel_master_parsed.json"
    json_path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {json_path}")

    emit_vfd_master_dart(data, ROOT / "lib" / "data" / "datasources" / "vfd_master_from_excel.dart")
    emit_vendor_models_dart(
        data, ROOT / "lib" / "data" / "datasources" / "vendor_models_from_excel.dart"
    )
    print("Wrote Dart data files. Run: flutter analyze lib/data/datasources/")


if __name__ == "__main__":
    main()
